-- Oracle APEX Lead Tracker Starter
-- Tables, lookup data, and Jira sync stubs for an APEX-based lead tracking app.

-- ============================================================
-- 1) LOOKUP TABLES
-- ============================================================

create table product_catalog (
    product_id           number generated by default as identity primary key,
    product_name         varchar2(200) not null,
    product_family       varchar2(100),
    business_unit        varchar2(100),
    is_active            varchar2(1) default 'Y' not null check (is_active in ('Y','N')),
    created_at           timestamp default systimestamp not null,
    updated_at           timestamp
);

create unique index ux_product_catalog_name on product_catalog (upper(product_name));

create table lead_state_lu (
    state_code           varchar2(30) primary key,
    state_name           varchar2(100) not null,
    sort_order           number not null,
    is_terminal          varchar2(1) default 'N' not null check (is_terminal in ('Y','N'))
);

create table priority_lu (
    priority_code        varchar2(10) primary key,
    priority_name        varchar2(100) not null,
    sort_order           number not null
);

create table engagement_lu (
    engagement_code      varchar2(20) primary key,
    engagement_name      varchar2(100) not null,
    sort_order           number not null
);

create table readiness_lu (
    readiness_code       varchar2(30) primary key,
    readiness_name       varchar2(100) not null,
    sort_order           number not null
);

-- ============================================================
-- 2) CORE TABLES
-- ============================================================

create table lead_request (
    lead_id                  number generated by default as identity primary key,
    lead_number              varchar2(30) not null,
    customer_name            varchar2(255) not null,
    customer_account         varchar2(255),
    customer_contact_name    varchar2(255),
    customer_contact_email   varchar2(320),
    source_employee_name     varchar2(255) not null,
    source_employee_email    varchar2(320),
    product_primary_id       number,
    state_code               varchar2(30) not null,
    priority_code            varchar2(10) not null,
    engagement_code          varchar2(20) not null,
    readiness_code           varchar2(30) not null,
    use_case_summary         varchar2(4000),
    transcript_clob          clob,
    jira_issue_key           varchar2(50),
    jira_issue_url           varchar2(1000),
    jira_sync_status         varchar2(30) default 'PENDING' not null,
    jira_last_sync_at        timestamp,
    lead_owner               varchar2(255),
    created_by               varchar2(255),
    created_at               timestamp default systimestamp not null,
    updated_by               varchar2(255),
    updated_at               timestamp,
    constraint uq_lead_request_lead_number unique (lead_number),
    constraint fk_lead_product foreign key (product_primary_id) references product_catalog(product_id),
    constraint fk_lead_state foreign key (state_code) references lead_state_lu(state_code),
    constraint fk_lead_priority foreign key (priority_code) references priority_lu(priority_code),
    constraint fk_lead_engagement foreign key (engagement_code) references engagement_lu(engagement_code),
    constraint fk_lead_readiness foreign key (readiness_code) references readiness_lu(readiness_code)
);

create index ix_lead_request_state on lead_request(state_code);
create index ix_lead_request_priority on lead_request(priority_code);
create index ix_lead_request_product on lead_request(product_primary_id);
create index ix_lead_request_jira on lead_request(jira_issue_key);

create table lead_product_interest (
    lead_product_id          number generated by default as identity primary key,
    lead_id                  number not null,
    product_id               number not null,
    interest_level           varchar2(20) not null,
    created_at               timestamp default systimestamp not null,
    constraint fk_lpi_lead foreign key (lead_id) references lead_request(lead_id) on delete cascade,
    constraint fk_lpi_product foreign key (product_id) references product_catalog(product_id),
    constraint ck_lpi_interest check (interest_level in ('PRIMARY','SECONDARY','FUTURE'))
);

create unique index ux_lpi_unique on lead_product_interest (lead_id, product_id);

create table lead_interaction (
    interaction_id           number generated by default as identity primary key,
    lead_id                  number not null,
    interaction_type         varchar2(50) not null,
    interaction_notes        clob,
    transcript_clob          clob,
    author_name              varchar2(255),
    author_email             varchar2(320),
    jira_comment_id          varchar2(100),
    created_at               timestamp default systimestamp not null,
    constraint fk_interaction_lead foreign key (lead_id) references lead_request(lead_id) on delete cascade
);

create index ix_lead_interaction_lead on lead_interaction(lead_id);

create table lead_state_history (
    history_id               number generated by default as identity primary key,
    lead_id                  number not null,
    old_state_code           varchar2(30),
    new_state_code           varchar2(30) not null,
    changed_by               varchar2(255),
    changed_at               timestamp default systimestamp not null,
    change_reason            varchar2(4000),
    constraint fk_lsh_lead foreign key (lead_id) references lead_request(lead_id) on delete cascade
);

create index ix_lsh_lead on lead_state_history(lead_id);

create table jira_sync_log (
    sync_id                  number generated by default as identity primary key,
    lead_id                  number,
    jira_issue_key           varchar2(50),
    action_name              varchar2(50) not null,
    status                   varchar2(30) not null,
    request_payload          clob,
    response_payload         clob,
    error_message            varchar2(4000),
    created_at               timestamp default systimestamp not null
);

-- ============================================================
-- 3) SAMPLE LOOKUP DATA
-- ============================================================

insert into lead_state_lu values ('NEW','New',10,'N');
insert into lead_state_lu values ('UNDER_REVIEW','Under Review',20,'N');
insert into lead_state_lu values ('NEEDS_MORE_INFO','Needs More Information',30,'N');
insert into lead_state_lu values ('QUALIFIED','Qualified',40,'N');
insert into lead_state_lu values ('PRODUCT_EVALUATION','Product Evaluation',50,'N');
insert into lead_state_lu values ('SOLUTION_PROPOSED','Solution Proposed',60,'N');
insert into lead_state_lu values ('PILOT_POC','Pilot / POC',70,'N');
insert into lead_state_lu values ('NEGOTIATION','Negotiation',80,'N');
insert into lead_state_lu values ('WON','Won',90,'Y');
insert into lead_state_lu values ('LOST','Lost',100,'Y');
insert into lead_state_lu values ('ON_HOLD','On Hold',110,'N');
insert into lead_state_lu values ('DUPLICATE','Duplicate',120,'Y');
insert into lead_state_lu values ('CLOSED','Closed',130,'Y');

insert into priority_lu values ('P1','P1 - Critical',10);
insert into priority_lu values ('P2','P2 - High',20);
insert into priority_lu values ('P3','P3 - Medium',30);
insert into priority_lu values ('P4','P4 - Low',40);

insert into engagement_lu values ('0','0 - No Contact',10);
insert into engagement_lu values ('1','1 - Initial Discussion',20);
insert into engagement_lu values ('2','2 - Active Engagement',30);
insert into engagement_lu values ('3','3 - Executive Sponsorship',40);
insert into engagement_lu values ('4','4 - Pilot Commitment',50);
insert into engagement_lu values ('5','5 - Purchase Intent',60);
insert into engagement_lu values ('6','6 - Customer',70);

insert into readiness_lu values ('UNKNOWN','Unknown',10);
insert into readiness_lu values ('REQ_GATHERING','Requirements Gathering',20);
insert into readiness_lu values ('ARCH_DEFINED','Architecture Defined',30);
insert into readiness_lu values ('ENV_READY','Environment Ready',40);
insert into readiness_lu values ('INTEGRATION','Integration In Progress',50);
insert into readiness_lu values ('PILOT_RUNNING','Pilot Running',60);
insert into readiness_lu values ('PROD_READY','Production Ready',70);
insert into readiness_lu values ('PRODUCTION','Production',80);

commit;

-- ============================================================
-- 4) SEQUENCES / NUMBERING
-- ============================================================

create sequence seq_lead_number start with 1000 increment by 1 nocache;

create or replace trigger bi_lead_request
before insert on lead_request
for each row
begin
    if :new.lead_number is null then
        :new.lead_number := 'L-' || to_char(seq_lead_number.nextval);
    end if;

    if :new.created_at is null then
        :new.created_at := systimestamp;
    end if;
end;
/

create or replace trigger bu_lead_request
before update on lead_request
for each row
begin
    :new.updated_at := systimestamp;
end;
/

-- ============================================================
-- 5) PACKAGE STUB FOR JIRA SYNC
--    Replace auth + endpoint details with your Jira environment.
-- ============================================================

create or replace package lead_jira_pkg as
    procedure create_jira_issue(
        p_lead_id        in number,
        p_issue_key       out varchar2,
        p_issue_url       out varchar2
    );

    procedure add_jira_comment(
        p_lead_id        in number,
        p_comment_text   in clob
    );

    procedure sync_lead_update(
        p_lead_id        in number,
        p_action_name    in varchar2,
        p_comment_text   in clob default null
    );
end lead_jira_pkg;
/

create or replace package body lead_jira_pkg as
    procedure create_jira_issue(
        p_lead_id        in number,
        p_issue_key       out varchar2,
        p_issue_url       out varchar2
    ) is
    begin
        -- Stub: call Jira REST API POST /rest/api/3/issue
        -- Store returned issue key and browse URL.
        p_issue_key := null;
        p_issue_url  := null;
    end;

    procedure add_jira_comment(
        p_lead_id        in number,
        p_comment_text   in clob
    ) is
    begin
        -- Stub: call Jira REST API POST /rest/api/3/issue/{issueIdOrKey}/comment
        null;
    end;

    procedure sync_lead_update(
        p_lead_id        in number,
        p_action_name    in varchar2,
        p_comment_text   in clob default null
    ) is
        l_issue_key varchar2(50);
    begin
        select jira_issue_key
          into l_issue_key
          from lead_request
         where lead_id = p_lead_id;

        if l_issue_key is null then
            create_jira_issue(p_lead_id => p_lead_id, p_issue_key => l_issue_key, p_issue_url => null);
        else
            add_jira_comment(p_lead_id => p_lead_id, p_comment_text => p_comment_text);
        end if;

        insert into jira_sync_log (lead_id, jira_issue_key, action_name, status, created_at)
        values (p_lead_id, l_issue_key, p_action_name, 'PENDING', systimestamp);
    exception
        when others then
            insert into jira_sync_log (lead_id, jira_issue_key, action_name, status, error_message, created_at)
            values (p_lead_id, l_issue_key, p_action_name, 'ERROR', sqlerrm, systimestamp);
            raise;
    end;
end lead_jira_pkg;
/

-- ============================================================
-- 6) APEX PAGE PLAN
--    Suggested page set:
--    1  Dashboard
--    2  Lead Interactive Report
--    3  Lead Form
--    4  Lead Detail / Timeline
--    5  Product Catalog
--    6  Admin Lookup Maintenance
-- ============================================================

prompt Starter script created.
